pipeline {
	agent any

	environment {
		envA = 'env-in-pipeline'
	}

	parameters {
		string(name:'Greeting', defaultValue:'Hello', description:'my first param in pipeline')
	}

	stages{
		stage('first-build'){
			environment {
				envB = 'env-in-stage-build'
			}

			steps{
				sh 'echo first-build start'
				sh 'npm --version'
				echo "*** Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
				echo "*** build-stage envA:${envA}, envB:${envB}"

				echo "${params.Greeting} World"
				echo "paramString1: ${params.paramString1}"
			}
		}
		stage('Test'){
			steps{
				sh 'echo Testing...'
				// sh "echo *** test-stage envA:${envA}, envB:${envB} || true"
			}
		}
		stage('Deploy'){
			steps{
				sh 'echo Deploy...'
			}
		}
	}

	post {
		always{
			echo '==== post-always ==='
		}
		failure{
			echo '==== post-failure ==='
		}
		unstable{
			echo '==== post-unstable ==='
		}
		success{
			echo '==== post-success ==='
		}
		changed{
			echo '==== post-changed ==='
		}
	}
}
