pipeline {
	agent any

	stages{
		stage('first-build'){
			steps{
				sh 'echo first-build start'
				sh 'npm --version'
			}
		}
		stage('Test'){
			steps{
				sh 'echo Testing...'
			}
		}
		stage('Deploy'){
			steps{
				sh 'echo Deploy...'
			}
		}
	}

}
